# Generated by Django 3.1.2 on 2021-01-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CaptionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('user_id', models.CharField(max_length=100)),
                ('comments', models.TextField()),
                ('caption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caption_site.caption')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1500)),
                ('human_annotation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PresetOpinionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback2PresetOpinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caption_site.feedback')),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caption_site.presetopinionoption')),
            ],
        ),
        migrations.AddField(
            model_name='caption',
            name='caption_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caption_site.captionmodel'),
        ),
        migrations.AddField(
            model_name='caption',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caption_site.image'),
        ),
    ]
