# Generated by Django 3.1.2 on 2021-01-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_site', '0002_auto_20210130_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/caption_site'),
        ),
    ]
