# Generated by Django 3.1.2 on 2021-01-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_site', '0003_auto_20210130_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionmodel',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='captionmodel',
            name='url',
            field=models.URLField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comments',
            field=models.TextField(default='N/A'),
        ),
    ]
