# Generated by Django 3.1.2 on 2021-01-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_site', '0004_auto_20210131_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captionmodel',
            name='url',
            field=models.URLField(default='https://arnab-api.github.io/'),
        ),
    ]
