# Generated by Django 3.1.2 on 2021-02-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caption_site', '0005_auto_20210131_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='presetopinionoption',
            name='is_positive',
            field=models.BooleanField(default=False),
        ),
    ]
